CREATE TABLE IF NOT EXISTS PRODUCTS(
PRODUCT_ID TEXT,
PRODUCT_NAME TEXT,
SUPPLIER_ID TEXT,
CATEGORY_ID TEXT,
UNIT TEXT,
PRICE REAL
);
INSERT INTO PRODUCTS(PRODUCT_ID,PRODUCT_NAME,SUPPLIER_ID,CATEGORY_ID,UNIT,PRICE)VALUES
('1','CHAIS','1','1','10 BOXES*BAGS',12),
('2','CHAYS','5','7','34 BOXES*BAGS',45),
('3','TGNRT','2','1','10 BOXES*BAGS',22),
('4','CHHTYIS','1','1','10 BOXES*BAGS',52),
('5','CojAIS','5','4','10 BOXES*BAGS',44);
SELECT COUNT(PRODUCT_ID) AS Product_Count
FROM PRODUCTS;
SELECT AVG(PRICE) AS Average_Count
FROM PRODUCTS;
SELECT SUM(PRICE) AS Total_price
FROM PRODUCTS;

